### ISSUE TITLE
Add modularity in Tweet2Map.py

### ISSUE THREAD

**Issue by ljvmiranda921** [pbrotoisworo/tweet2map#1]
Hi @Esparko , Thanks for this great project! 

I often see your posts in the "How's your biyahe" Facebook group and I appreciate your analyses,
I've noticed that one upcoming feature you're planning to do is:

> Streamline main script by utilizing more classes and functions 

I have some ideas for improving modularity in this project and to ensure that it is "pythonic." Some of these might entail a hefty amount of refactoring, but hopefully they can be helpful to you:

1. **Try writing with respect to [PEP8](https://www.python.org/dev/peps/pep-0008/)**: This is the Python style guide and ensures uniform code across projects. Methods (e.g. `tweetParse`) should use underscores, variables (e.g. `CsvFile`, `DataRow`) should always be small caps with underscores if necessary, etc.

2. **Contain the whole logic of the main script inside `main()`**. Then you can call it as

```python
if __name__ = "__main__":
    main()
```

This is the usual way of [invoking command-line applications](https://stackoverflow.com/questions/419163/what-does-if-name-main-do). You can also check out `argparse` or `click` libraries for command-line arguments

3. **Use `logging` module instead of `print()` statements**. Logging statements can be [more informative](https://stackoverflow.com/questions/6918493/in-python-why-use-logging-instead-of-print) in case there are bugs in your system. 

4. **Improve project scaffolding**. Hopefully this [short guide](https://python-packaging.readthedocs.io/en/latest/) can help you. This would dramatically improve the robustness and ease-of-use of this project, and maybe easier for contributors to check in.

5. **Try storing `data_mmda_traffic_alerts.csv` in an SQLite database** CSV files may become heavy once it's populated. Atleast with an SQL database we can do some SQL querying whenever we want to. 

Again, thanks a lot for this wonderful work and I'm looking forward for this project to succeed. Hopefully I can drop some PRs every now and then!

**Comment by Esparko** [comment]
I appreciate your comments @ljvmiranda921! I'm still learning Python and this is my first major coding project so it's very messy compared to professional code.

I'll definitely look into some of your suggestions such as using an SQLite database, logging, and making it more Pythonic. Especially because I'm also not sure how this code will work once it scales up because when I run this I'm working with more and more locations and the CSV file is getting bigger and bigger.

**Comment by pbrotoisworo** [comment]
The code has  been rewritten from scratch and is significantly more modular and easier to understand. #3

**Comment by ljvmiranda921** [comment]
Hey thanks for this! Definitely a huge improvement!
P.S. Sent you an email panji.p.broto@gmail.com
